version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: nexusmind_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: nexusmind_redis
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    volumes:
      - redis_data:/data
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: nexusmind_minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console UI port
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  nexusmind-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexusmind_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
    env_file:
      - ./.env
    environment:
      # These values are specific to the docker environment and override .env
      - PYTHONPATH=/app/src
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - MINIO_ENDPOINT=http://minio:9000
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug
    depends_on:
      - postgres
      - redis
      - minio
    # restart: unless-stopped

volumes:
  postgres_data: {}
  redis_data: {}
  minio_data: {} 