version: '3.8'

services:
  api-server:
    image: xinhaozhang23/nexusmind-api-server:latest
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    env_file:
      - .env
    networks:
      - nexusmind_network

  worker:
    image: xinhaozhang23/nexusmind-worker:latest
    command: poetry run celery -A nexusmind.celery_app worker --loglevel=info -Q brain_item_queue,file_processing_queue
    volumes:
      - ./storage:/app/storage
      - ./src:/app/src
    env_file:
      - .env
    networks:
      - nexusmind_network

  websocket-gateway:
    image: xinhaozhang23/nexusmind-websocket-gateway:latest
    ports:
      - "8001:8001"
    environment:
      - FASTAPI_URL=http://api-server:8000/chat
    env_file:
      - .env.prod
    networks:
      - nexusmind_network

  nginx:
    image: xinhaozhang23/nexusmind-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api-server
      - websocket-gateway
    networks:
      - nexusmind_network

networks:
  nexusmind_network:
    driver: bridge