version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: nexusmind_postgres
    environment:
      POSTGRES_USER: nexusmind_user
      POSTGRES_PASSWORD: nexusmind_password
      POSTGRES_DB: nexusmind_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: nexusmind_redis
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    volumes:
      - redis_data:/data
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: nexusmind_minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console UI port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  nexusmind-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexusmind_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
    environment:
      - PYTHONPATH=/app/src
    env_file:
      - .env
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
      - redis
      - minio
    # restart: unless-stopped

volumes:
  postgres_data: {}
  redis_data: {}
  minio_data: {} 