version: '3.8'

services:
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: nexusmind_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nexusmind-api
      - websocket-gateway
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: nexusmind_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: nexusmind_redis
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nexusmind-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexusmind_api
    # The port is no longer exposed to the host. Nginx will handle traffic.
    # ports:
    #   - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
      - ./brains:/app/brains
      - ./storage:/app/storage
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app/src
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      # MINIO_ENDPOINT is removed as minio service is temporarily disabled
    # The command should use port 5001 as referenced in nginx.conf
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 5001 --log-level debug
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexusmind_worker
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
      - ./brains:/app/brains
      - ./storage:/app/storage
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app/src
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      # MINIO_ENDPOINT is removed as minio service is temporarily disabled
    command: poetry run celery -A nexusmind.celery_app.app worker --loglevel=info
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  websocket-gateway:
    build:
      context: ./websocket_gateway
      dockerfile: Dockerfile
    container_name: websocket-gateway
    # No ports need to be exposed to the host. Nginx communicates internally.
    restart: always
    environment:
      - FASTAPI_URL=http://nexusmind-api:5001/chat
      - API_KEY=your-super-secret-key
    depends_on:
      - nexusmind-api

volumes:
  postgres_data: {}
  redis_data: {} 