version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Mount storage and brains directories to persist data
      - ./storage:/app/storage
      - ./brains:/app/brains 