"""Create initial tables

Revision ID: c1a696167488
Revises:
Create Date: 2025-07-10 08:16:01.583775

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1a696167488"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("s3_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "PROCESSING", "SUCCESS", "FAILURE", name="filestatusenum"
            ),
            nullable=False,
        ),
        sa.Column("brain_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_file_brain_id"), "file", ["brain_id"], unique=False)
    op.create_index(op.f("ix_file_file_name"), "file", ["file_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_file_name"), table_name="file")
    op.drop_index(op.f("ix_file_brain_id"), table_name="file")
    op.drop_table("file")
    op.execute("DROP TYPE filestatusenum")
    # ### end Alembic commands ###
