name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_DUMMY }}
        STORAGE_BASE_PATH: /tmp/nexusmind-storage
        CELERY_BROKER_URL: redis://localhost:6379/0
        CELERY_RESULT_BACKEND: redis://localhost:6379/0
        API_KEYS: ${{ secrets.API_KEYS_DUMMY }}
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: nexusmind
        REDIS_HOST: localhost
        REDIS_PORT: 6379
      run: |
        poetry run pytest

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API Server image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nexusmind-api-server:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/nexusmind-api-server:latest

      - name: Build and push Worker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nexusmind-worker:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/nexusmind-worker:latest
            
      - name: Build and push Nginx image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./nginx/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nexusmind-nginx:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/nexusmind-nginx:latest

      - name: Build and push WebSocket Gateway image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./websocket_gateway/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nexusmind-websocket-gateway:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/nexusmind-websocket-gateway:latest