name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install

    - name: Lint with flake8
      run: poetry run flake8 .

    - name: Check formatting with black
      run: poetry run black --check .

    - name: Check imports with isort
      run: poetry run isort --check-only .

    - name: Run tests with pytest
      run: poetry run pytest 